In [ ]:
import pandas as pd

In [ ]:
# Load the dataset
file_path = '/content/heart_disease_health_indicators_BRFSS2015 2 (1).csv'
df = pd.read_csv(file_path)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22474 entries, 0 to 22473
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   HeartDiseaseorAttack  22474 non-null  int64
 1   HighBP                22474 non-null  int64
 2   HighChol              22474 non-null  int64
 3   CholCheck             22474 non-null  int64
 4   BMI                   22474 non-null  int64
 5   Smoker                22474 non-null  int64
 6   Stroke                22474 non-null  int64
 7   Diabetes              22473 non-null  float64
 8   PhysActivity          22473 non-null  float64
 9   Fruits                22473 non-null  float64
 10  Veggies               22473 non-null  float64
 11  HvyAlcoholConsump     22473 non-null  float64
 12  AnyHealthcare         22473 non-null  float64
 13  NoDocbcCost           22473 non-null  float64
 14  GenHlth               22473 non-null  float64
 15  MentHlth              22473 non-null  float64
 16  PhysHlth              22473 non-null  float64
 17  DiffWalk              22473 non-null  float64
 18  Sex                   22473 non-null  float64
 19  Age                   22473 non-null  float64
 20  Education             22473 non-null  float64
 21  Income                22473 non-null  float64
dtypes: float64(15), int64(7)
memory usage: 3.8 MB

In [ ]:
df.describe()

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
count,22474.000000,22474.000000,22474.000000,22474.000000,22474.000000,22474.000000,22474.000000,22473.000000,22473.000000,22473.000000,...,22473.000000,22473.000000,22473.000000,22473.000000,22473.000000,22473.000000,22473.000000,22473.000000,22473.000000,22473.000000
mean,0.092729,0.427694,0.421020,0.961467,28.182255,0.430942,0.043383,0.312909,0.765407,0.624928,...,0.942064,0.098207,2.552174,3.448627,4.557024,0.178703,0.438526,7.880390,5.020469,5.959551
std,0.290059,0.494755,0.493734,0.192484,6.245456,0.495219,0.203723,0.711424,0.423753,0.484152,...,0.233628,0.297601,1.102948,7.646833,8.965866,0.383112,0.496218,3.125394,1.044459,2.158772
min,0.000000,0.000000,0.000000,0.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
25%,0.000000,0.000000,0.000000,1.000000,24.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,6.000000,4.000000,5.000000
50%,0.000000,0.000000,0.000000,1.000000,27.000000,0.000000,0.000000,0.000000,1.000000,1.000000,...,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,8.000000,5.000000,7.000000
75%,0.000000,1.000000,1.000000,1.000000,31.000000,1.000000,0.000000,0.000000,1.000000,1.000000,...,1.000000,0.000000,3.000000,2.000000,4.000000,0.000000,1.000000,10.000000,6.000000,8.000000
max,1.000000,1.000000,1.000000,1.000000,92.000000,1.000000,1.000000,2.000000,1.000000,1.000000,...,1.000000,1.000000,5.000000,30.000000,30.000000,1.000000,1.000000,13.000000,6.000000,8.000000

In [ ]:
df.head()

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0,1,1,1,40,1,0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0,0,0,0,25,1,0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0,1,1,1,28,0,0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0,1,0,1,27,0,0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0,1,1,1,24,0,0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0

In [ ]:
df.nunique() #review the unique values in each column to identify potential categorical variables

HeartDiseaseorAttack     2
HighBP                   2
HighChol                 2
CholCheck                2
BMI                     61
Smoker                   2
Stroke                   2
Diabetes                 3
PhysActivity             2
Fruits                   2
Veggies                  2
HvyAlcoholConsump        2
AnyHealthcare            2
NoDocbcCost              2
GenHlth                  5
MentHlth                31
PhysHlth                31
DiffWalk                 2
Sex                      2
Age                     13
Education                6
Income                   8
dtype: int64

In [ ]:
# Converting binary and ordinal variables to 'category' type
binary_columns = [
    'HeartDiseaseorAttack', 'HighBP', 'HighChol', 'CholCheck', 'Smoker', 'Stroke',
    'PhysActivity', 'Fruits', 'Veggies', 'HvyAlcoholConsump', 'AnyHealthcare',
    'NoDocbcCost', 'DiffWalk', 'Sex'
]

ordinal_columns = {
    'GenHlth': [1, 2, 3, 4, 5],  # 1=Excellent, 5=Poor
    'Education': [1, 2, 3, 4, 5, 6],  # 1=No schooling, 6=College graduate
    'Income': [1, 2, 3, 4, 5, 6, 7, 8],  # Income levels from 1 to 8
    'Age': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]  # Age groups
}

# Convert binary columns to category
for col in binary_columns:
    df[col] = df[col].astype('category')

# Convert ordinal columns to category with ordered=True
for col, order in ordinal_columns.items():
    df[col] = pd.Categorical(df[col], categories=order, ordered=True)

In [ ]:
duplicate_rows = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicate_rows}")

Number of duplicate rows: 471

In [ ]:
# Remove duplicates
df_cleaned = df.drop_duplicates()

# Check how many rows were removed
rows_removed = df.shape[0] - df_cleaned.shape[0]

# Display number of rows removed and new shape
print(f"Rows removed: {rows_removed}")
print(f"New shape of dataset: {df_cleaned.shape}")

Rows removed: 471
New shape of dataset: (22003, 22)

In [ ]:
# Perform a final check on the dataset structure
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22474 entries, 0 to 22473
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   HeartDiseaseorAttack  22474 non-null  category
 1   HighBP                22474 non-null  category
 2   HighChol              22474 non-null  category
 3   CholCheck             22474 non-null  category
 4   BMI                   22474 non-null  int64
 5   Smoker                22474 non-null  category
 6   Stroke                22474 non-null  category
 7   Diabetes              22473 non-null  float64
 8   PhysActivity          22473 non-null  category
 9   Fruits                22473 non-null  category
 10  Veggies               22473 non-null  category
 11  HvyAlcoholConsump     22473 non-null  category
 12  AnyHealthcare         22473 non-null  category
 13  NoDocbcCost           22473 non-null  category
 14  GenHlth               22473 non-null  category
 15  MentHlth              22473 non-null  float64
 16  PhysHlth              22473 non-null  float64
 17  DiffWalk              22473 non-null  category
 18  Sex                   22473 non-null  category
 19  Age                   22473 non-null  category
 20  Education             22473 non-null  category
 21  Income                22473 non-null  category
dtypes: category(18), float64(3), int64(1)
memory usage: 1.1 MB

In [ ]:
df_cleaned.to_csv('cleaned_dataset.csv', index=False)